[package]
name = "du"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = { version = "0.10.6" }
tempfile = "3.2"
clap = { version = "4.4.6", features = ["derive"] }
